// Insert plausible `topic_assessments` rows for every active topic so the
// dashboard has assessment data without running the LLM reviewer. Deterministic
// per topic id; re-runnable (wipes prior rows under this assessor first).
//
// Usage: pnpm db:mock-assess

import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';

const ASSESSOR_ID = 'mock:gold-rotation';
const TRIGGERED_BY = 'mock-assess-topics';

type Character = 'attention' | 'opportunity' | 'noteworthy' | 'calm';
const CHARACTERS: Character[] = ['attention', 'opportunity', 'noteworthy', 'calm'];

interface TopicRow {
  id: string;
  label: string;
  description: string | null;
  member_count: number;
  source_count: number;
  velocity_24h: number;
  velocity_7d_avg: number;
  spread_24h: number;
  unique_authors_7d: number;
  activity_trend: string;
  last_activity_at: string | null;
}

function hash01(s: string): number {
  const h = createHash('sha256').update(s).digest();
  // First 4 bytes → uint32 → [0, 1)
  const n = h.readUInt32BE(0);
  return n / 0x100000000;
}

function pickCharacter(topicId: string): Character {
  const idx = Math.floor(hash01(`${topicId}:char`) * CHARACTERS.length);
  return CHARACTERS[idx]!;
}

function pickScore(character: Character, topicId: string): number {
  const jitter = hash01(`${topicId}:score`) * 0.2;
  const base: Record<Character, number> = {
    attention: 0.78,
    opportunity: 0.55,
    noteworthy: 0.42,
    calm: 0.18,
  };
  return Math.round((base[character] + jitter - 0.1) * 100) / 100;
}

function buildSummary(topic: TopicRow, character: Character): string {
  const label = topic.label || topic.id;
  const parts = [
    `Mock-Assessment für „${label}".`,
    topic.description ? `Kontext: ${topic.description}` : null,
    `Aktuell ${topic.member_count} Records aus ${topic.source_count} Quellen, Trend ${topic.activity_trend}.`,
    character === 'attention'
      ? 'Mehrere Quellen schlagen koordiniert auf — sofortiger Blick empfohlen.'
      : character === 'opportunity'
        ? 'Wiederkehrender Wunsch mit Produkt-Hebel; Roadmap-Kandidat.'
        : character === 'noteworthy'
          ? 'Stabile Hintergrundaktivität — beobachten, aber nicht eskalieren.'
          : 'Ruhig; aktuell keine Aktion nötig.',
  ];
  return parts.filter((p): p is string => Boolean(p)).join(' ');
}

function buildKeySignals(topic: TopicRow, character: Character): string[] {
  const signals: string[] = [];
  if (topic.spread_24h >= 2)
    signals.push(`Cross-Source-Spread: ${topic.spread_24h} Quellen in 24h`);
  if (topic.velocity_24h > 0)
    signals.push(`Velocity 24h: ${topic.velocity_24h} (Schnitt 7d: ${topic.velocity_7d_avg})`);
  if (topic.unique_authors_7d > 0)
    signals.push(`${topic.unique_authors_7d} unterschiedliche Autoren in 7 Tagen`);
  signals.push(`Trend: ${topic.activity_trend}`);
  if (character === 'attention') signals.push('Mock-Heuristik: koordinierter Multi-Source-Hit');
  if (character === 'opportunity') signals.push('Mock-Heuristik: Produktwunsch-Muster erkannt');
  return signals.slice(0, 6);
}

async function main(): Promise<void> {
  if (existsSync('.env')) process.loadEnvFile();

  const { sql } = await import('../packages/db/src/client');

  const topics = await sql<TopicRow[]>`
    SELECT id, label, description, member_count, source_count,
           velocity_24h, velocity_7d_avg, spread_24h, unique_authors_7d,
           activity_trend, last_activity_at
    FROM topics
    WHERE status = 'active'
    ORDER BY id ASC
  `;

  if (topics.length === 0) {
    console.log('No active topics found — run pnpm db:preseed-topics first.');
    await sql.end();
    return;
  }

  const targets = topics;
  console.log(`Mocking assessments for all ${targets.length} active topics.`);

  await sql.begin(async (tx) => {
    await tx`DELETE FROM topic_assessments WHERE assessor = ${ASSESSOR_ID}`;

    const now = new Date().toISOString();
    for (const t of targets) {
      const character = pickCharacter(t.id);
      const escalation = pickScore(character, t.id);
      const reasoning = {
        summary: {
          text: buildSummary(t, character),
          covers_record_ids: [],
        },
        key_signals: buildKeySignals(t, character),
        key_artifacts: [],
        additional_notes: `Generated by ${TRIGGERED_BY}; not from live LLM reviewer.`,
      };
      await tx`
        INSERT INTO topic_assessments
          (topic_id, assessor, assessed_at, character, escalation_score, reasoning, triggered_by)
        VALUES
          (${t.id}, ${ASSESSOR_ID}, ${now},
           ${character}, ${escalation},
           ${JSON.stringify(reasoning)}::jsonb, ${TRIGGERED_BY})
      `;
    }
  });

  for (const t of targets) {
    console.log(`  ${t.id}  ${t.label}`);
  }

  await sql.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
